image: ruby:latest

stages:
  - build
  - deploy


build-prod:
  stage: build
  script:
    - echo "module.exports = 'prod';">currentConfig.js
  artifacts:
    untracked: true
    paths:
      - *
  only:
    - deployment-heroku-prod

build-integ:
  stage: build
  script:
    - echo "module.exports = 'integ';">currentConfig.js
  artifacts:
    untracked: true
    paths:
      - *
  except:
    - deployment-heroku-prod

deploy-heroku-prod:
  stage: deploy
  environment: heroku production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --skip_cleanup=true --provider=heroku --app=salatia-app-api --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - deployment-heroku-prod

deploy-heroku-integ:
  stage: deploy
  environment: heroku integration
  when: manual
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --skip_cleanup=true --provider=heroku --app=salatia-app-api-integ --api-key=$HEROKU_INTEGRATION_API_KEY
  except:
    - deployment-heroku-prod
